app/main/models.py
from app.ext import db

class Shop(db.Model):
    shop_id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(512),index=True)
    sub_title = db.Column(db.String(512),index=True)
    original_price = db.Column(db.Integer)
    promote_price = db.Column(db.Integer)
    stock = db.Column(db.Integer)
    cate_id = db.Column(db.Integer,db.ForeignKey('cate.cid'))
    create_date = db.Column(db.DateTime)
    cate = db.relationship('Cate', back_populates='shops')

class Cate(db.Model):
    cid = db.Column(db.Integer,primary_key=True)
    cname = db.Column(db.String(64),index=True,nullable=True,unique=True)
    shops = db.relationship('Shop',lazy='dynamic',back_populates='cate')


app/main/views.py
import datetime
import json
import time

from flask import Blueprint, render_template, jsonify ,request,redirect

from app.ext import db
from .models import Shop ,Cate

main = Blueprint('main', __name__)

@main.route('/all/')
def all_1():
    return redirect('/main/all/1/10/')


@main.route('/all/<int:page>/<int:size>/',methods=['GET','POST'])
def all(page,size):
    # shops = Shop.query.all()
    paginate = Shop.query.order_by(Shop.shop_id).paginate(page=page,per_page=size,error_out=False)
    shops = paginate.items
    return render_template('main.html',shops=shops,paginate=paginate)


# 增
@main.route('/add/')
def add():
    return render_template('add.html')

@main.route('/index/',methods = ['POST','GET'])
def index():
    if request.method == 'GET':
        return render_template('index.html')
    elif request.method == 'POST':
        name = request.form.get('name')
        sub_title = request.form.get('sub_title')
        original_price = request.form.get('original_price')
        promote_price = request.form.get('promote_price')
        stock = request.form.get('stock')
        cate_id = request.form.get('cate_id')
        shop = Shop(name=name,
                   sub_title=sub_title,
                   original_price=original_price,
                   promote_price=promote_price,
                    stock=stock,
                    cate_id=cate_id,
                   )
        db.session.add(shop)
        db.session.commit()
        return render_template('index.html')

@main.route('/save/')
def save_all():
    objects = []
    for i in range(151,201):
        objects.append(Shop(name='test'+str(i),
               sub_title='test_1'+str(i),
               original_price=100+i,
               promote_price=50+i,
               stock=4,
               cate_id=4,))
    db.session.bulk_save_objects(objects)
    db.session.commit()
    return '批量保存'

@main.route('/savecate/')
def savecate():
    objects = []
    for i in range(1,5):
        objects.append(Cate(
            cname='TEXT'+str(i)
        ))
    db.session.bulk_save_objects(objects)
    db.session.commit()
    return '批量保存'

# 删
@main.route('/delate/<int:id>/')
def delate(id):
    shop = Shop.query.filter(Shop.shop_id==id).first()
    db.session.delete(shop)
    db.session.commit()
    return render_template('delate.html',shop=shop)


# 改
@main.route('/update/<int:id>')
def update(id):
    return render_template('update.html',id=id)

@main.route('/index1/',methods = ['POST','GET'])
def index1():
    if request.method == 'GET':
        return render_template('index.html')
    elif request.method == 'POST':
        name = request.form.get('name')
        sub_title = request.form.get('sub_title')
        original_price = request.form.get('original_price')
        promote_price = request.form.get('promote_price')
        stock = request.form.get('stock')
        cate_id = request.form.get('cate_id')
        shop_id = request.form.get('shop_id')
        Shop.query.filter(Shop.shop_id==shop_id).update({Shop.name:name,
                                                         Shop.sub_title:sub_title,
                                                         Shop.original_price:original_price,
                                                         Shop.promote_price:promote_price,
                                                         Shop.stock:stock,
                                                         Shop.cate_id:cate_id})
        db.session.commit()
        return render_template('index.html')



# 查
import logging
@main.route('/find/',methods= ['GET','POST'])
def find():
    if request.method == 'GET':
        return render_template('find.html')
    if request.method == 'POST':
        text = request.form.get('text')
        shops= Shop.query.filter(Shop.name.ilike('%'+text+'%')).all()
        return render_template('find_end.html',shops=shops)
    # cates =Cate.query.all()
    # for shop in cates[0].shops:
    #     logging.debug(shop.name)
    #     # print(shop.name)
    #
    # shop = Shop.query.get(1)
    # print(shop.name)
    # print(shop.cate.cname)
    # shops = Cate.query.get(1).shops
    # for shop in shops:
    #     print(shop.name)
    # print(shops)
    # return '111'11111

@main.route('/cate/')
def cate():
    cates = Cate.query.all()
    return render_template('cate.html',cates=cates)

@main.route('/cate/<int:cid>/')
def cateshop(cid):
    print(cid)
    shops = Cate.query.get(cid==cid).shops
    return render_template('cateshop.html',shops=shops)

app/upload/views.py
from flask import Blueprint, request, render_template

from app.ext import images

upload_blue = Blueprint('upload', __name__)

@upload_blue.route('/img/', methods=['GET','POST'])
def upload_img():
    if request.method == 'POST':
        images.save(request.files['img'])
        return '111'
    elif request.method == 'GET':
        return render_template('upload.html')

app/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form enctype="multipart/form-data" method="post" action="http://127.0.0.1:9000/main/index/">
        商品名称：<input name="name"/><br/>
        商品别名: <input name="sub_title"/><br/>
        销售价格: <input name="original_price"/><br/>
        促销价格: <input name="promote_price"/><br/>
        库存量: <input name="stock"/><br/>
        仓库: <input name="cate_id"/><br/>
        <input type="submit" value="添加"/>
    </form>
</body>
</html>

app/templates/cate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul>
        {% for cate in cates %}
            <li><a href="{{ url_for('main.cate') }}{{ cate.cid }}/">{{ cate.cname }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

app/templates/cateshop.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul>
        {% for shop in shops %}
            <li>{{ shop.name }}</li>
        {% endfor %}
    </ul>
</body>
</html>

app/templates/delate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>删除成功</h1>
<h1><a href="http://127.0.0.1:9000/main/all/">返回</a></h1>
</body>
</html>

app/templates/find.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post" action="{{ url_for('main.find') }}" enctype="multipart/form-data">
        <input type="text" name="text"/>
        <input type="submit" value="查询"/>
    </form>
</body>
</html>

app/templates/find_end.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style type="text/css">
        table {
            width: 100%;
            border-collapse: collapse;
        }

        td, th {
            border: 1px solid blue;
            text-align: center;
        }
    </style>
</head>
<body>
<table>
    <tr>
        <th><a href="http://127.0.0.1:9000/main/add/">增加</a></th>
    </tr>
    <tr>
        <th><a href="{{ url_for('main.all_1') }}">返回</a></th>
    </tr>
    <tr>
        <th>商品名称编号</th>
        <th>商品名称</th>
        <th>商品别名</th>
        <th>销售价格</th>
        <th>促销价格</th>
        <th>更改</th>
    </tr>
    {% for shop in shops %}
    <tr>
        <th >{{ shop.shop_id }}</th>
        <th>{{ shop.name }}</th>
        <th>{{ shop.sub_title }}</th>
        <th>{{ shop.original_price }}</th>
        <th>{{ shop.promote_price }}</th>
        <th><a href="http://127.0.0.1:9000/main/update/{{ shop.shop_id }}">修改</a>
            <a href="http://127.0.0.1:9000/main/delate/{{ shop.shop_id }}/">删除</a>
        </th>
    </tr>
    {% endfor %}

</table>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>添加/修改成功</h1>
    <h1><a href="{{ url_for('main.all_1') }}">返回</a></h1>
</body>
</html>

app/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style type="text/css">
        table {
            width: 100%;
            border-collapse: collapse;
        }

        td, th {
            border: 1px solid blue;
            text-align: center;
        }
        ul{
            text-align: center;
            margin: 0px;
            padding: 0px;
        }
        ul li {

            float: left;
            list-style: none;
            margin: 10px;
            padding: 0px;

        }
        ul a {
            text-decoration: none;
            font-size: 30px;
            cursor: pointer;
            color: black;
        }

    </style>
</head>
<body>
<table>
    <tr>
        <th>
            <form method="post" action="{{ url_for('main.find') }}" enctype="multipart/form-data">
                <input type="text" name="text"/>
                <input type="submit" value="查询"/>
            </form>
        </th>
    </tr>
    <tr>
        <th><a href="http://127.0.0.1:9000/main/add/">增加</a></th>
    </tr>
    <tr>
        <th>商品名称编号</th>
        <th>商品名称</th>
        <th>商品别名</th>
        <th>销售价格</th>
        <th>促销价格</th>
        <th>更改</th>
    </tr>
    {% for shop in shops %}
    <tr>
        <th >{{ shop.shop_id }}</th>
        <th>{{ shop.name }}</th>
        <th>{{ shop.sub_title }}</th>
        <th>{{ shop.original_price }}</th>
        <th>{{ shop.promote_price }}</th>
        <th><a href="http://127.0.0.1:9000/main/update/{{ shop.shop_id }}">修改</a>
            <a href="http://127.0.0.1:9000/main/delate/{{ shop.shop_id }}/">删除</a>
        </th>
    </tr>
    {% endfor %}

</table>
<ul>
    <li><a href="{{ url_for('main.all',page=1,size=10) }}">首页</a></li>
    <li>
        <a href="
        {% if paginate.has_prev %}
            {{ url_for('main.all',page=paginate.page - 1,size=10) }}
        {% else %}
            #
        {% endif %}
                ">上页</a>
    </li>
    {% for p in paginate.iter_pages(left_edge=0,left_current=5,right_edge=0,right_current=5) %}
        {% if p  %}
            {% if p == paginate.page %}
                <li><a style="color: red">{{ p }}</a></li>
            {% else %}
                <li><a href="{{ url_for('main.all',page=p,size=10) }}">{{ p }}</a></li>
            {% endif %}
        {% endif %}
    {% endfor %}
    <li>
        <a href="
        {% if paginate.has_next %}
            {{ url_for('main.all',page=paginate.page + 1,size=10) }}
        {% else %}
            #
        {% endif %}
                ">下页</a>
    </li>
    <li><a href="{{ url_for('main.all',page=paginate.pages,size=10) }}" >尾页</a></li>
</ul>

</body>
</html>

app/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style type="text/css">
        #shop_id{
            display: none;
        }
    </style>
</head>
<body>
    <form enctype="multipart/form-data" method="post" action="http://127.0.0.1:9000/main/index1/">
    商品名称：<input name="name"/><br/>
    商品别名: <input name="sub_title"/><br/>
    销售价格: <input name="original_price"/><br/>
    促销价格: <input name="promote_price"/><br/>
    库存量: <input name="stock"/><br/>
    仓库: <input name="cate_id"/><br/>
        <input name="shop_id" value="{{ id }}" id="shop_id"/>
    <input type="submit" value="修改"/>
    </form>
</body>
</html>

app/templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{{ url_for('upload.upload_img') }}" method="post" enctype="multipart/form-data">
        <input type="file" name="img">
        <input type="submit" value="上传">
    </form>
</body>
</html>